### ISSUE TITLE
Can't send commands to stdin on Windows

### ISSUE THREAD

**Issue by JAndritsch** [Sobesednik/node-exiftool#2]
First and foremost, thank you for putting this together. I have been messing around with Exiftool in a Node application recently and trying to get my head wrapped around how to properly send and receive calls to/from Exiftool with the -stay_open flag enabled. Your library makes this really easy to manage.

During my testing of this lib, I noticed that I was able to send and receive data through stdin/stdout on my Mac without any issues but couldn't get it working on Windows. The problem appears to be related to the hardcoded `\n` characters when sending commands to `stdin`. Unix and Windows have different values for end of line characters (`\n` and `\r\n` respectively).

This problem can easily be fixed by replacing all instances of a hardcoded `\n` character with `require('os').EOL`.

**Comment by TotallyInformation** [comment]
Ah, I really need this too. I'm just starting to look at putting together a photo renaming tool to use with Node-Red. Your library would be brilliant because I want to be able to extract data such as the Camera name not just EXIF dates and Exiftool is great for that. But I'd also want to be able to offer the ability to set various standard EXIF/IPTC metadata fields such as copyright.

But, I need all of this to work on Windows! Not just Mac/Linux.

**Comment by JAndritsch** [comment]
I just submitted a PR for this.
